### ISSUE TITLE
readme.txt and apps-readme.txt under test subdirectory are better combined and in markdown format

### ISSUE THREAD

**Issue by zqzhang** [otcshare/iot-rest-api-server#11]

**Comment by gvancuts** [comment]
Is this the right place to track such feature requests/improvements?

**Comment by zqzhang** [comment]
Hmm, if Jira is preferable, I can file one there too.

**Comment by gvancuts** [comment]
I actually don’t have a strong preference, I just want to make sure that things logged here wouldn’t fall into a blackhole. @poussa , what do you think?

**Comment by poussa** [comment]
Yes, I agree. The 2 files should be merged.

**Comment by poussa** [comment]
REPO MOVED TO https://github.com/01org/iot-rest-api-server
